apiVersion: apps/v1
kind: Deployment
metadata:
  name: warriorcrm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warriorcrm
  template:
    metadata:
      labels:
        app: warriorcrm
    spec:
      containers:
      - name: warriorcrm
        image: gcr.io/YOUR_PROJECT_ID/warriorcrm:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: warriorcrm-service
spec:
  type: NodePort
  selector:
    app: warriorcrm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warriorcrm-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: warrior.rebtel.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: warriorcrm-service
                port:
                  number: 80
